services:
  big-bear-homeassistant:
    image: linuxserver/homeassistant:latest # Use the latest Home Assistant image from Linuxserver
    container_name: big-bear-homeassistant # Set a custom container name
    environment:
      - PUID=1000 # UID of the 'abc' user
      - PGID=1000 # GID of the 'abc' user
      - TZ=UTC # Set the timezone for Home Assistant. Replace with your timezone, e.g., "America/New_York"
    volumes:
      - ha_config_data:/config # Bind mount a volume for Home Assistant configuration data
      - /var/run/dbus:/var/run/dbus:ro # Read-only bind mount for D-Bus to enable Bluetooth integrations
    restart: unless-stopped # Ensure the container restarts unless explicitly stopped
    network_mode: host # Use the host network mode

volumes:
  ha_config_data:
    name: ha_config_data # Use the custom volume name
    driver: local # Use the local driver for the Home Assistant configuration volume
